"""Show a local public-area model over a video file or RTSP stream in real time."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import subprocess
import time

os.environ.setdefault("OPENCV_FFMPEG_CAPTURE_OPTIONS", "rtsp_transport;tcp")

import cv2
import numpy as np
import torch

from label_property_video import parse_crop
from train_public_area import TinyUNet


def choose_device(requested: str) -> torch.device:
    if requested != "auto":
        return torch.device(requested)
    if torch.cuda.is_available():
        return torch.device("cuda")
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def load_model(model_path: Path, device: torch.device) -> tuple[TinyUNet, int, float]:
    checkpoint = torch.load(model_path, map_location=device)
    model = TinyUNet(int(checkpoint.get("base_channels", 16))).to(device)
    model.load_state_dict(checkpoint["state_dict"])
    model.eval()
    return model, int(checkpoint.get("image_size", 384)), float(checkpoint.get("threshold", 0.5))


def predict(model: TinyUNet, frame: np.ndarray, image_size: int, device: torch.device) -> np.ndarray:
    height, width = frame.shape[:2]
    rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    resized = cv2.resize(rgb, (image_size, image_size), interpolation=cv2.INTER_AREA)
    tensor = torch.from_numpy(resized.transpose(2, 0, 1)).unsqueeze(0).float().to(device) / 255.0
    with torch.no_grad():
        probability = torch.sigmoid(model(tensor))[0, 0].cpu().numpy()
    return cv2.resize(probability, (width, height), interpolation=cv2.INTER_LINEAR)


def probe_stream(stream: str) -> tuple[int, int]:
    """Use FFprobe instead of OpenCV, which often cannot open camera RTSP on macOS."""
    command = ["ffprobe", "-v", "error", "-print_format", "json", "-show_streams"]
    if stream.lower().startswith("rtsp://"):
        command.extend(["-rtsp_transport", "tcp"])
    command.append(stream)
    result = subprocess.run(command, capture_output=True, text=True, timeout=15)
    try:
        streams = json.loads(result.stdout or "{}").get("streams", [])
    except ValueError as error:
        raise RuntimeError("FFprobe returned invalid stream information.") from error
    for item in streams:
        if item.get("codec_type") == "video":
            return int(item["width"]), int(item["height"])
    details = (result.stderr or "no video stream returned").strip()
    raise RuntimeError(f"Could not read video stream with FFprobe: {details}")


def open_ffmpeg_pipe(stream: str) -> subprocess.Popen:
    command = ["ffmpeg", "-loglevel", "error"]
    if stream.lower().startswith("rtsp://"):
        command.extend(["-rtsp_transport", "tcp"])
    command.extend(["-i", stream, "-f", "rawvideo", "-pix_fmt", "bgr24", "pipe:1"])
    return subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, bufsize=10**8)


def main() -> None:
    parser = argparse.ArgumentParser(description="Preview the public-area segmentation model over local video or RTSP.")
    parser.add_argument("--model", default="models/public-area/model.pt", help="Model generated by train_public_area.py")
    parser.add_argument("--stream", default=os.environ.get("CAMERA_GARAGE_RTSP_URL"), help="Local video path or RTSP URL. Defaults to CAMERA_GARAGE_RTSP_URL.")
    parser.add_argument("--crop", type=parse_crop, default=None, help="Optional x1,y1,x2,y2 crop for the PTZ lens in a combined stream")
    parser.add_argument("--threshold", type=float, default=None, help="Public-area probability threshold; default uses model value")
    parser.add_argument("--alpha", type=float, default=0.42, help="Opacity of the orange public-area overlay")
    parser.add_argument("--every_n_frames", type=int, default=1, help="Run inference every N frames and reuse the latest mask between frames")
    parser.add_argument("--device", choices=("auto", "cpu", "mps", "cuda"), default="auto")
    args = parser.parse_args()
    if not args.stream:
        parser.error("provide --stream or set CAMERA_GARAGE_RTSP_URL")
    if not 0 < args.alpha <= 1 or args.every_n_frames < 1:
        parser.error("alpha must be in (0, 1] and every_n_frames must be at least 1")

    device = choose_device(args.device)
    model, image_size, saved_threshold = load_model(Path(args.model), device)
    threshold = args.threshold if args.threshold is not None else saved_threshold
    source_width, source_height = probe_stream(args.stream)
    frame_size = source_width * source_height * 3
    is_rtsp = args.stream.lower().startswith("rtsp://")
    pipe = open_ffmpeg_pipe(args.stream)

    window_name = "Public-area model preview"
    cv2.namedWindow(window_name, cv2.WINDOW_NORMAL | cv2.WINDOW_KEEPRATIO)
    print(f"Previewing with {Path(args.model).name} on {device.type}; threshold={threshold:.2f}. Press Q to quit.")
    frame_count = 0
    probability: np.ndarray | None = None
    while True:
        raw = pipe.stdout.read(frame_size)
        if len(raw) != frame_size:
            if not is_rtsp:
                break
            if pipe.poll() is None:
                pipe.kill()
            print("Camera stream disconnected; reconnecting in 2 seconds.")
            time.sleep(2)
            pipe = open_ffmpeg_pipe(args.stream)
            continue
        source = np.frombuffer(raw, dtype=np.uint8).reshape((source_height, source_width, 3)).copy()
        frame_count += 1
        if args.crop:
            x1, y1, x2, y2 = args.crop
            height, width = source.shape[:2]
            if not (0 <= x1 < x2 <= width and 0 <= y1 < y2 <= height):
                raise RuntimeError(f"Crop {args.crop} is outside the stream's {width}x{height} frame.")
            frame = source[y1:y2, x1:x2]
        else:
            frame = source

        if probability is None or frame_count % args.every_n_frames == 0:
            probability = predict(model, frame, image_size, device)
        public = probability >= threshold
        canvas = frame.copy()
        public_color = np.array((0, 165, 255), dtype=np.float32)
        canvas[public] = ((1 - args.alpha) * canvas[public] + args.alpha * public_color).astype(np.uint8)
        coverage = float(public.mean())
        cv2.putText(canvas, f"public area: {coverage:.1%}  threshold: {threshold:.2f}  Q: quit", (14, 28), cv2.FONT_HERSHEY_SIMPLEX, 0.65, (255, 255, 255), 2)
        cv2.imshow(window_name, canvas)
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break

    if pipe.poll() is None:
        pipe.kill()
    cv2.destroyAllWindows()


if __name__ == "__main__":
    main()
